if (t_consumable > 0) {t_consumable--;}
if (t_facility > 0) {t_facility--;}
if (t_trainee > 0) {t_trainee--;}
if (t_battle > 0) {t_battle--;}
if (t_battle2 > 0) {t_battle2--;}
if (t_shake > 0) {t_shake--;}
if (t_shakeO > 0) {t_shakeO--;}
if (t_enemy > 0) {t_enemy--;}
if (t_enemyAttack > 0) {t_enemyAttack--;}
if (t_choice > 0) {t_choice--;}